### ISSUE TITLE
[FE] 비밀번호 재설정 - 사용자 인증

### ISSUE THREAD

**Issue by 2realzoo** [codestates-seb/seb42_main_015#15]
### 만들고자 하는 기능
- 비밀번호 재설정 - 사용자 인증

### 해당 기능을 구현하기 위해 할 일
1. [x] 이메일 인증 기능
2. [x] 이메일 유효성 검사
3. [x] 이메일로 받은 인증번호 입력
4. [x] 다음 버튼

### 예상 작업 시간
- 2h

**Comment by sienna0715** [comment]
레이아웃 완성
